apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-ci
  namespace: {{ .Values.namespace }}
spec:
  params:
    - name: APP_REPO
      default: {{ .Values.appRepo | quote }}
    - name: APP_REVISION
      default: {{ .Values.appRevision | quote }}
    - name: IMAGE_REPO
      default: {{ .Values.imageRepo | quote }}
    - name: GITOPS_REPO
      default: {{ .Values.gitopsRepo | quote }}
    - name: CHART_PATH
      default: {{ .Values.chartPath | quote }}
  workspaces:
    - name: shared
  tasks:
    - name: clone
      resolver: cluster
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.APP_REPO)
        - name: REVISION
          value: $(params.APP_REVISION)
      workspaces:
        - name: output
          workspace: shared

    - name: mvn-build
      runAfter: [clone]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: jib-maven
          - name: namespace
            value: openshift-pipelines
      params:
        - name: GOALS
          value:
            - -DskipTests
            - package
        - name: IMAGE
          value: quarkus-dev
      workspaces:
        - name: source
          workspace: shared

    - name: build-push
      runAfter: [mvn-build]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(params.IMAGE_REPO):$(tasks.clone.results.COMMIT)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: {{ .Values.tlsVerify | quote }}
      workspaces:
        - name: source
          workspace: shared
