apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-ci
  namespace: quarkus-dev
  labels:
    app.kubernetes.io/instance: quarkus-ci
spec:
  params:
    - name: APP_REPO
      type: string
      default: https://github.com/NateLove/quarkus-openshift.git
    - name: APP_REVISION
      type: string
      default: main
    - name: IMAGE_REPO
      type: string
      default: image-registry.openshift-image-registry.svc:5000/quarkus-dev/quarkus-openshift
    - name: GITOPS_REPO
      type: string
      default: https://github.com/NateLove/quarkus-openshift-gitops.git
    - name: CHART_PATH
      type: string
      default: helm/quarkus-app

  workspaces:
    - name: shared

  tasks:
    - name: clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.APP_REPO)
        - name: REVISION
          value: $(params.APP_REVISION)
      workspaces:
        - name: output        # git-clone expects this
          workspace: shared

    - name: mvn-build
      runAfter: [clone]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: jib-maven
          - name: namespace
            value: openshift-pipelines
      params:
        - name: GOALS
          value:
            - -DskipTests
            - package
        - name: IMAGE
          value: quarkus-dev
        - name: MAVEN_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-21:latest
      workspaces:
        - name: source        # jib-maven expects this
          workspace: shared

    - name: build-push
      runAfter: [mvn-build]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(params.IMAGE_REPO):$(tasks.clone.results.COMMIT)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: shared
