apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-ci
  namespace: quarkus-dev
spec:
  params:
    - name: APP_REPO
      type: string
      default: https://github.com/NateLove/quarkus-openshift.git
    - name: APP_REVISION
      type: string
      default: main
    - name: IMAGE_REPO
      type: string
      default: image-registry.openshift-image-registry.svc:5000/quarkus-dev/quarkus-openshift
    - name: MAVEN_IMAGE
      type: string
      default: registry.access.redhat.com/ubi9/openjdk-21:latest
  workspaces:
    - name: shared
    - name: maven-settings
    - name: maven-local-repo

  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.APP_REPO)
        - name: REVISION
          value: $(params.APP_REVISION)
      workspaces:
        - name: output
          workspace: shared

    - name: maven-build-and-push
      runAfter: [git-clone]
      taskRef:
        kind: Task
        name: maven
      params:
        - name: GOALS
          value:
            - -DskipTests
            - -Dquarkus.container-image.build=true
            - -Dquarkus.container-image.push=true
            - -Dquarkus.container-image.image=$(params.IMAGE_REPO):$(tasks.git-clone.results.commit)
            - package
        - name: MAVEN_IMAGE
          value: $(params.MAVEN_IMAGE)
      workspaces:
        - name: source
          workspace: shared
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo

