apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-ci
  namespace: quarkus-dev
spec:
  params:
    - name: APP_REPO
      type: string
      default: https://github.com/NateLove/quarkus-openshift.git
    - name: APP_REVISION
      type: string
      default: main
    - name: IMAGE_REPO
      type: string
      default: image-registry.openshift-image-registry.svc:5000/quarkus-dev/quarkus-openshift
    - name: MAVEN_IMAGE
      type: string
      default: registry.access.redhat.com/ubi9/openjdk-21:latest
  workspaces:
    - name: shared
    # (optional) speed up builds by caching the local ~/.m2 repo between tasks/runs
    - name: maven-cache
      optional: true

  tasks:
    - name: clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.APP_REPO)
        - name: REVISION
          value: $(params.APP_REVISION)
      workspaces:
        - name: output              # git-clone expects 'output'
          workspace: shared

    - name: maven-build-and-push
      runAfter: [clone]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven          # generic Maven ClusterTask
          - name: namespace
            value: openshift-pipelines
      params:
        # Quarkus drives the image build via its container-image-jib extension
        - name: GOALS
          value:
            - -DskipTests
            - -Dquarkus.container-image.build=true
            - -Dquarkus.container-image.push=true
            - -Dquarkus.container-image.image=$(params.IMAGE_REPO):$(tasks.clone.results.COMMIT)
            - package
        - name: MAVEN_IMAGE
          value: $(params.MAVEN_IMAGE)
      workspaces:
        - name: source             # 'maven' task expects 'source'
          workspace: shared
        - name: maven-settings     # optional in ClusterTask; safe to omit
          workspace: maven-cache
