{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quarkus-app
spec:
  to:
    kind: Service
    name: quarkus-app
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
  {{- end }}
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
{{- end }}
