apiVersion: v1
kind: Service
metadata:
  name: quarkus-app
  labels:
    app: quarkus-app
spec:
  selector:
    app: quarkus-app
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.containerPort }}
