image:
  repository: image-registry.openshift-image-registry.svc:5000/quarkus-dev/quarkus-openshift
  tag: 6e44e6177bbb6fd10c9ac4f4c391306342ffd2d2
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

route:
  enabled: true
  host: ""  # optional: set to a fixed host if you want
  tls:
    enabled: true
    termination: edge

env: []  # e.g. [{ name: QUARKUS_LOG_LEVEL, value: INFO }]
